/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.tienda.vista;

import com.tienda.dao.UsuarioDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Rec17
 */
public class AltaCajeroDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AltaCajeroDialog.class.getName());

    /**
     * Creates new form AltaCajeroDialog
     */
    public AltaCajeroDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal); //Establece la ventana padre, en este caso "MainFram"
        initComponents();
        jLabel1.putClientProperty("FlatLaf.style", "font: 24 'DearSans-Book'");
        
        jPasswordField1.putClientProperty("FlatLaf.style",
            "showRevealButton: true; " +
            "showCapsLock: true;");
        // Placeholders
        jTextField1.putClientProperty("JTextField.placeholderText", "Ingrese el nombre del nuevo cajero");
        jPasswordField1.putClientProperty("JTextField.placeholderText", "Ingrese contraseña de nuevo cajero");
        
        jLabel2.putClientProperty("FlatLaf.style", "font: 26 'DearSans-Book'");
        
        jLabel3.putClientProperty("FlatLaf.style", "font: 26 'DearSans-Book'");
        
        //jButton1.putClientProperty("JButton.buttonType", "roundRect");
        jButton1.putClientProperty("FlatLaf.style", "font: 20 'DearSans-Book'");
        jButton1.setText("<html><body style='margin-top: 2px;'>Guardar</body></html>");
        
        //jButton2.putClientProperty("JButton.buttonType", "roundRect");
        jButton2.putClientProperty("FlatLaf.style", "font: 20 'DearSans-Book'");
        jButton2.setText("<html><body style='margin-top: 2px;'>Aceptar</body></html>");
        setLocationRelativeTo(parent); // Centrar la ventana modal en el centro del frame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(505, 500));
        setName("Dar de alta nuevo cajero"); // NOI18N
        setPreferredSize(new java.awt.Dimension(505, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre del cajero");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 310, -1));

        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 310, -1));

        jLabel3.setText("Usuarios existentes");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jButton1.setText("Guardar");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        jButton2.setText("Aceptar");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Contraseña", "Rol"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 440, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 1. Validar que los campos no estén vacíos
        String usuario = jTextField1.getText().trim();
        String password = new String(jPasswordField1.getPassword()); // JPasswordField

        if (usuario.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, llena todos los campos", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return; // Detiene la ejecución para que no cierre la ventana
        }

        // Mandar los datos a la base de datos usando tu DAO
        UsuarioDAO cajeroDao = new UsuarioDAO();
        //boolean exito = cajeroDao.registrarCajero(usuario, password);
        boolean exito = true;
        // 3. Procesar el resultado
        if (exito) {
            JOptionPane.showMessageDialog(this, "¡Cajero registrado con éxito!", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            // 🚀 El toque final: Cerramos y liberamos la memoria del JDialog
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar el cajero en la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                AltaCajeroDialog dialog = new AltaCajeroDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
