/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tienda.vista;

import com.tienda.dao.UsuarioDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Rec17
 */
public class CajeroLoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form CajeroLoginPanel
     */
    public CajeroLoginPanel() {
        initComponents();
        // Asociar la tecla enter con envío de credenciales
        jTextField1.addActionListener(e -> jButton2ActionPerformed(null));
        jPasswordField1.addActionListener(e -> jButton2ActionPerformed(null));

        jButton1.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("icons/backward.svg", 24, 24));
        jLabel1.putClientProperty("FlatLaf.style", "font: 56 'DearSans-Book'");
        jLabel1.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("icons/user.svg", (float) 6.0));
        // Centrar el contenido (icono + texto) horizontalmente
        
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        // Mover el texto abajo del icono
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        // Darle espacio de separación entre el icono y el texto
        jLabel1.setIconTextGap(20);
        // Icono de checkmark para enviar la contraseña
        jButton2.putClientProperty("JButton.buttonType", "roundRect");
        jButton2.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("icons/check.svg", 24, 24));
        
        jPasswordField1.putClientProperty("FlatLaf.style",
            "showRevealButton: true; " +
            "showCapsLock: true;");
        // Placeholders
        jTextField1.putClientProperty("JTextField.placeholderText", "Ingrese su usuario");
        jPasswordField1.putClientProperty("JTextField.placeholderText", "Ingresa tu contraseña");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Atrás");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 100, 40));

        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 600, 240, -1));

        jButton2.addActionListener(this::jButton2ActionPerformed);
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 600, 40, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cajero");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 510, 400));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 550, 240, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Obtener la info del frame principal
        MainFrame framePrincipal = (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (framePrincipal != null) {
            // Instanciar el nuevo panel del Login de Administrador
            LoginPanel LoginPanel = new LoginPanel(); //Para cada ventana, cambiar su constructor

            // Mandar a hacer el intercambio
            framePrincipal.cambiarPanel(LoginPanel);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String usuarioTxt = jTextField1.getText().trim();
        String passwordTxt = new String(jPasswordField1.getPassword());

        if (usuarioTxt.isEmpty() || passwordTxt.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
            jTextField1.requestFocus();
            return;
        }

        // Conexión con la DAO
        UsuarioDAO usuarioDao = new UsuarioDAO();
        int rol = usuarioDao.autenticar(usuarioTxt, passwordTxt);

        switch (rol) {
            case -1 -> {
                JOptionPane.showMessageDialog(this, "Contraseña y/o usuarios incorrectos.", "Acceso Denegado", JOptionPane.ERROR_MESSAGE);
                jPasswordField1.setText("");
                jTextField1.requestFocus();
            }
            case 0 -> {
                // Caso cuando el usuario es Cajero
                MainFrame framePrincipal = (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
                if (framePrincipal != null) {
                    // Instanciar el nuevo panel de apertura de caja para el cajero
                    AperturaCaja AperturaCaja = new AperturaCaja(); //Para cada ventana, cambiar su constructor

                    // Mandar a hacer el intercambio
                    framePrincipal.cambiarPanel(AperturaCaja);
                }
            }
            case 1 -> {
                // Caso cuando el usuario es administrador y quiere entrar a cajero
                JOptionPane.showMessageDialog(this,
                        "Acceso denegado: Tu rol de administrador no corresponde para esta sección \nPor favor, usa la ventana de administración",
                        "Permisos incorrectos", JOptionPane.WARNING_MESSAGE);
                jPasswordField1.setText("");
                jTextField1.setText("");
            }
            default -> {
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
