/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tienda.vista;

import com.tienda.dao.ConfiguracionDAO;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Rec17
 */
public class InventarioPanel extends javax.swing.JPanel {

    /**
     * Creates new form InventarioPanel
     */
    public InventarioPanel() {
        initComponents();

        // Crea el menú flotante
        JPopupMenu menuUsuario = new JPopupMenu();

        //Crea la opción de cerrar sesión
        JMenuItem itemCerrarSesion = new JMenuItem("Cerrar sesión");
        // Icono
        // itemCerrarSesion.setIcon(Icono); //Por si quiero importar un icono, pero 
        // no lo dice Diseño

        // Agregar la acción al botón de cerrar sesión
        itemCerrarSesion.addActionListener(e -> {
            MainFrame framePrincipal = (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
            if (framePrincipal != null) {
                // Instanciar el nuevo panel del Login de Administrador
                LoginPanel LoginPanel = new LoginPanel(); //Para cada ventana, cambiar su constructor

                // Mandar a hacer el intercambio
                framePrincipal.cambiarPanel(LoginPanel);
            }
        });
        // Agregar el evento de clic al ícono de administrador
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // .show(componente_origen, coordenada_X, coordenada_Y)
                // X en 0 y Y justo al final de la altura del ícono para cuadrarlo bien
                menuUsuario.show(jLabel1, 0, jLabel1.getHeight());
            }
        });
        // Meter el ítem al menú
        menuUsuario.add(itemCerrarSesion);
        //Establece la fuente a tamaño 56
        jLabel2.putClientProperty("FlatLaf.style", "font: 56 'DearSans-Book'");
        jLabel1.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("icons/admin.svg", (float) 3.0));
        // Centrar el contenido (icono + texto) horizontalmente
//        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//
//        // Mover el texto abajo del icono (por defecto Swing lo pone a la derecha)
//        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);
//        
        

        // Darle espacio de separación entre el icono y el texto
        jButton1.setText("<html><body style='margin-top: 2px;'>Dar de alta nuevo producto</body></html>");

        jButton1.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("icons/plus.svg", (float) 1.0));
        jButton1.putClientProperty("FlatLaf.style", "font: 20 'DearSans-Book'");
        jButton1.putClientProperty("JButton.buttonType", "roundRect");
        
        jButton2.setText("<html><body style='margin-top: 2px;'>Añadir Cajero</body></html>");
        jButton2.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("icons/useradd.svg", (float) 1.0));
        jButton2.putClientProperty("FlatLaf.style", "font: 20 'DearSans-Book'");
        jButton2.putClientProperty("JButton.buttonType", "roundRect");
        
        jButton3.setText("<html><body style='margin-top: 2px;'>Modificar IVA</body></html>");
        jButton3.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("icons/iva.svg", (float) 1.0));
        jButton3.putClientProperty("FlatLaf.style", "font: 20 'DearSans-Book'");
        jButton3.putClientProperty("JButton.buttonType", "roundRect");
        
        jLabel2.setIconTextGap(20);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Administrador");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 460, -1));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 130, 130));

        jButton1.setText("Dar de alta nuevo producto");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 370, -1));

        jButton2.setText("Agregar cajero");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 270, -1));

        jButton3.setText("Modificar IVA");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, 260, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "SKU", "Precio", "Precio de compra", "Acciones", "Stock actual", "Stock mínimo"
            }
        ));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 1090, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Instancia de ConfiguracionDAO y hace la query a la DB
        ConfiguracionDAO configDao = new ConfiguracionDAO();
        int ivaActual = configDao.getIVA();
        // Spinner (ValorInicial, Mínimo, Máximo, Paso/Incremento)
        // Numero 16 como valor inicial con rango de 0 a 100 y avanza de 1 en 1
        SpinnerNumberModel modeloIva = new SpinnerNumberModel(ivaActual, 0, 100, 1);
        JSpinner spinnerIva = new JSpinner(modeloIva);

        // Hacer que el texto del spinner termine con el símbolo de porcentaje
        JSpinner.NumberEditor editor = new JSpinner.NumberEditor(spinnerIva, "#'%'");
        spinnerIva.setEditor(editor);

        // Meter el spinner dentro de un JDialog modal usando JOptionPane
        // Crea la ventana pequeña, centrada y con botones de OK/Cancelar
        int opcion = JOptionPane.showOptionDialog(
                this, // Ventana padre (bloquea el MainFrame)
                spinnerIva, // Componente que se va a mostrar dentro
                "Modificar porcentaje de IVA", // Título de la ventanita
                JOptionPane.OK_CANCEL_OPTION, // Botones debajo
                JOptionPane.QUESTION_MESSAGE, // Ícono de la ventana
                null, null, null
        );

        // Procesado de la respuesta del usuario
        if (opcion == JOptionPane.OK_OPTION) {
            // Obtenemos el valor numérico directamente
            int nuevoIva = (int) spinnerIva.getValue();

            if (configDao.modificarIVA(nuevoIva)) {
                JOptionPane.showMessageDialog(this, "IVA actualizado en la base de datos", "Exito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar el IVA", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Buscar el frame principal que sostiene esta ventana modal
        java.awt.Frame parentFrame = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);

        // Instanciamos nuestro diálogo personalizado (parent, modal)
        AltaCajeroDialog dialog = new AltaCajeroDialog(parentFrame, true);

        // Mostrarlo en ventana
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

                                               


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
