/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package com.tienda.vista;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GradientPaint;
import java.awt.RenderingHints;

/**
 *
 * @author Rec17
 */
public class LoginPanel extends javax.swing.JPanel {

    /** Creates new form LoginPanel */
    public LoginPanel() {
        initComponents(); // Netbeans crea los componentes aquí
        //Establece la fuente a tamaño 56
        this.setOpaque(false);
        jLabel1.putClientProperty("FlatLaf.style", "font: 56 'Arial Rounded MT Bold'");
        //Redondeo de botón, es necesario que el botón tenga una proporción 1:1
        jButton1.putClientProperty("JButton.buttonType", "roundRect");
        jButton1.putClientProperty("FlatLaf.style", "font: 43 'New Peninim MT'");
        jButton1.setFocusable(false); //Para que no se coloree el borde del botón
        jButton1.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("icons/adminn.svg", (float) 4.0));
        
        jLabel2.putClientProperty("FlatLaf.style", "font: 36 'Arial Rounded MT Bold'");
        
        jButton2.putClientProperty("JButton.buttonType", "roundRect");
        jButton2.putClientProperty("FlatLaf.style", "font: 43 'New Peninim MT'");
        jButton2.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("icons/user1.svg", (float) 4.0));
        jButton2.setFocusable(false);
        
    }
    @Override
    protected void paintComponent(Graphics g) {
        // Convertimos el objeto Graphics a Graphics2D para acceder a funciones avanzadas de renderizado
        Graphics2D g2d = (Graphics2D) g.create();
        
        // Habilitar Antialiasing para que la transición de colores se vea fluida y limpia
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        
        // Definir los colores usando tus códigos Hexadecimales
        Color colorInicio = Color.decode("#F0F2F4"); // Rosa arriba
        Color colorFin = Color.decode("#F0F2F4");    // Azul abajo
        
        // Crear el degradado vertical: (0, 0) es la esquina superior, (0, getHeight()) es el límite inferior
        GradientPaint degradadoVertical = new GradientPaint(
                0, 0, colorInicio, 
                0, getHeight(), colorFin
        );
        
        // Aplicar el lienzo de pintura y rellenar el rectángulo de este panel
        g2d.setPaint(degradadoVertical);
        g2d.fillRect(0, 0, getWidth(), getHeight());
        
        g2d.dispose(); // Liberar los recursos gráficos inmediatamente
        super.paintComponent(g);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(165, 104, 188));

        jLabel1.setBackground(new java.awt.Color(250, 247, 251));
        jLabel1.setFont(new java.awt.Font("New Peninim MT", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(165, 104, 188));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIENVENIDO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(165, 104, 188));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("IDENTIFICARSE");

        jButton1.setBackground(new java.awt.Color(250, 247, 251));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(123, 63, 160));
        jButton1.setText("ADMINISTRADOR");
        jButton1.setToolTipText("");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setIconTextGap(30);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(250, 247, 251));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jButton2.setForeground(new java.awt.Color(123, 63, 160));
        jButton2.setText("CAJERO");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setIconTextGap(30);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Obtener la info del frame principal
        MainFrame framePrincipal = (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (framePrincipal != null) {
            // Instanciar el nuevo panel del Login de Administrador
            AdminLoginPanel panelAdmin = new AdminLoginPanel();

            // Mandar a hacer el intercambio
            framePrincipal.cambiarPanel(panelAdmin);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Obtener la info del frame principal
        MainFrame framePrincipal = (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (framePrincipal != null) {
            // Instanciar el nuevo panel del Login de Administrador
            CajeroLoginPanel panelCajero = new CajeroLoginPanel();

            // Mandar a hacer el intercambio
            framePrincipal.cambiarPanel(panelCajero);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
