/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tienda.vista;

import javax.swing.JPanel;

/**
 *
 * @author Rec17
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                confirmarCierre();
            }
        });
    }

    // Evita que Alt+F4 o el botón de cerrar tiren la aplicación sin avisar,
    // dejando un turno de caja abierto o una venta a medias en curso.
    private void confirmarCierre() {
        boolean turnoAbierto = com.tienda.util.Sesion.getInstancia().getIdTurno() > 0;

        String mensaje = turnoAbierto
                ? "Tienes un turno de caja abierto. Si cierras la aplicación sin hacer el cierre de caja, "
                        + "el turno quedará abierto en el sistema. ¿Deseas salir de todos modos?"
                : "¿Seguro que deseas cerrar la aplicación?";

        boolean confirmado = ConfirmacionDialog.confirmarAccionDestructiva(this, "Confirmación", mensaje, "Salir");
        if (confirmado) {
            System.exit(0);
        }
    }
    public void cambiarPanel(JPanel nuevoPanel) {
        this.getContentPane().removeAll();  // Borra el panel actual (LoginPanel)
        this.getContentPane().add(nuevoPanel, java.awt.BorderLayout.CENTER); // Añade el nuevo panel en el centro
        this.getContentPane().revalidate(); // Reajusta los cálculos de diseño
        this.getContentPane().repaint();    // Repinta los pixeles en la pantalla
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inventarioPanel1 = new com.tienda.vista.InventarioPanel();
        ventasPanel1 = new com.tienda.vista.VentasPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().add(ventasPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.tienda.vista.InventarioPanel inventarioPanel1;
    private com.tienda.vista.VentasPanel ventasPanel1;
    // End of variables declaration//GEN-END:variables
}
