/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tienda.vista;

import javax.swing.JPanel;

/**
 *
 * @author Rec17
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }
    public void cambiarPanel(JPanel nuevoPanel) {
        this.getContentPane().removeAll();  // Borra el panel actual (LoginPanel)
        this.getContentPane().add(nuevoPanel, java.awt.BorderLayout.CENTER); // Añade el nuevo panel en el centro
        this.getContentPane().revalidate(); // Reajusta los cálculos de diseño
        this.getContentPane().repaint();    // Repinta los pixeles en la pantalla
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel2 = new com.tienda.vista.LoginPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(loginPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.tienda.vista.LoginPanel loginPanel2;
    // End of variables declaration//GEN-END:variables
}
