/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.tienda.vista;

import com.tienda.dao.ConfiguracionDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author karolina
 */
public class NuevoProductoDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NuevoProductoDialog.class.getName());

    /**
     * Creates new form NuevoProductoDialog
     */
    public NuevoProductoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jLabel2.putClientProperty("FlatLaf.style", "font: 19 'DearSans-Book'");
        nombre.putClientProperty("JTextField.placeholderText", "Nombre del producto");
        marca.putClientProperty("JTextField.placeholderText", "Marca");
        precio.putClientProperty("JTextField.placeholderText", "Precio");
        precioCompra.putClientProperty("JTextField.placeholderText", "Precio de compra");
        stockMinimo1.putClientProperty("JTextField.placeholderText", "Stock mínimo");
        stock.putClientProperty("JTextField.placeholderText", "Stock");
        tamano.putClientProperty("JTextField.placeholderText", "Tamaño");
        aceptar.putClientProperty("FlatLaf.style", "font: 15 'DearSans-Book'");
        aceptar.setText("<html><body style='margin-top: 2px;'>aceptar</body></html>");
 
        jLabel3.putClientProperty("FlatLaf.style", "font: 19 'DearSans-Book'");
        
//jButton2.putClientProperty("JButton.buttonType", "roundRect");
        agregarTipo.putClientProperty("FlatLaf.style", "font: 15 'DearSans-Book'");
        agregarTipo.setText("<html><body style='margin-top: 2px;'>Agregar tipo</body></html>");
        setLocationRelativeTo(parent);
         String Tamano=tamano.getText();    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoProducto = new javax.swing.JComboBox<>();
        agregarTipo = new javax.swing.JButton();
        precioCompra = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        stock = new javax.swing.JTextField();
        tamano = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        marca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        generarSku = new javax.swing.JButton();
        stockMinimo1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        SKUgen = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 30, 505, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setName("nuevoProducto"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tipoProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Refrescos", "Frituras", "Lacteos", "Dulces" }));
        tipoProducto.addActionListener(this::tipoProductoActionPerformed);
        getContentPane().add(tipoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 120, -1));

        agregarTipo.setText("Agregar tipo +");
        agregarTipo.addActionListener(this::agregarTipoActionPerformed);
        getContentPane().add(agregarTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        precioCompra.setText("Precio de compra");
        precioCompra.addActionListener(this::precioCompraActionPerformed);
        getContentPane().add(precioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 150, -1));

        precio.setText("Precio");
        precio.addActionListener(this::precioActionPerformed);
        getContentPane().add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 150, -1));

        stock.setText("Stock");
        stock.addActionListener(this::stockActionPerformed);
        getContentPane().add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 150, -1));

        tamano.setText("Tamaño");
        tamano.addActionListener(this::tamanoActionPerformed);
        getContentPane().add(tamano, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 150, -1));

        nombre.setText("Nombre del producto");
        nombre.addActionListener(this::nombreActionPerformed);
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 150, -1));

        marca.setText("Marca");
        marca.addActionListener(this::marcaActionPerformed);
        getContentPane().add(marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 150, -1));

        jLabel2.setText("Tipo de producto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 200, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        jLabel3.setText("Código de barras");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        aceptar.setText("Aceptar");
        aceptar.addActionListener(this::aceptarActionPerformed);
        getContentPane().add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        generarSku.setText("Generar SKU");
        generarSku.addActionListener(this::generarSkuActionPerformed);
        getContentPane().add(generarSku, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        stockMinimo1.setText("Stock mínimo");
        stockMinimo1.addActionListener(this::stockMinimo1ActionPerformed);
        getContentPane().add(stockMinimo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 150, -1));

        jScrollPane1.setViewportView(SKUgen);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarTipoActionPerformed
         String tipoProd=JOptionPane.showInputDialog("ingresa un nuevo tipo de producto: ");
        tipoProducto.addItem(tipoProd);
    }//GEN-LAST:event_agregarTipoActionPerformed

    private void precioCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioCompraActionPerformed
     /* try{    String PrecioCompra=precioCompra.getText();   
    double preciodouble=Double.parseDouble(PrecioCompra);
    }catch (NumberFormatException e){
        JOptionPane.showMessageDialog(this, "ingresar un número valido");
    }*/
    }//GEN-LAST:event_precioCompraActionPerformed

    private void precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioActionPerformed
     /*   try{    String Precio=precio.getText();   
    double preciodouble2=Double.parseDouble(Precio);
    }catch (NumberFormatException e){
        JOptionPane.showMessageDialog(this, "ingresar un número valido");
    }*/
    }//GEN-LAST:event_precioActionPerformed

    private void stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockActionPerformed
       /*  try{    String Precio=precioCompra.getText();   
    double preciodouble3=Double.parseDouble(Precio);
    }catch (NumberFormatException e){
        JOptionPane.showMessageDialog(this, "ingresar un número valido");
    }*/
    }//GEN-LAST:event_stockActionPerformed

    private void tamanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamanoActionPerformed
           // String Tamano=tamano.getText();        // TODO add your handling code here:

    }//GEN-LAST:event_tamanoActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
     //String NombreP=nombre.getText();
    }//GEN-LAST:event_nombreActionPerformed

    private void marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaActionPerformed
       // String Marca=marca.getText();       
    }//GEN-LAST:event_marcaActionPerformed

    private void tipoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoProductoActionPerformed
       // String productType=tipoProducto.getSelectedItem().toString();
    }//GEN-LAST:event_tipoProductoActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
      /* if (nombre.getText().trim().isEmpty() || marca.getText().trim().isEmpty() || tamano.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Los campos Nombre, Marca y Tamaño son requeridos.",
                    "Campos faltantes", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            String tipoProd = JOptionPane.showInputDialog("ingresa un nuevo tipo de producto: ");
            tipoProducto.addItem(tipoProd);
            String Tamano = tamano.getText();
            try {
                String PrecioCompra = precioCompra.getText();
                double preciodouble = Double.parseDouble(PrecioCompra);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "ingresar un número valido");
            }
            try {
                String Precio = precio.getText();
                double preciodouble2 = Double.parseDouble(Precio);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "ingresar un número valido");
            }
            try {
                String Precio = precioCompra.getText();
                double preciodouble3 = Double.parseDouble(Precio);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "ingresar un número valido");
            }
            String NombreP = nombre.getText();
            String productType = tipoProducto.getSelectedItem().toString();
         
            String sku = txtSkuResultado.getText().trim();
            if (sku.equals("---") || sku.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "El SKU no se ha generado correctamente.", "Error de SKU", javax.swing.JOptionPane.ERROR_MESSAGE);
                
                return;
            }
            com.tienda.dao.ProductoDAO prodDAO=new com.tienda.dao.ProductoDAO();
            boolean guardadoExitoso=prodDAO.guardarProducto(tipoProducto, nombre, marca, tamano, precioCompra, precio, stock, stockMinimo1);
            if(guardadoExitoso){
                javax.swing.JOptionPane.showMessageDialog(this, "¡Producto registrado y guardado correctamente!");
                
                
            }else{
              javax.swing.JOptionPane.showMessageDialog(this, "No se pudo registrar el producto en la base de datos.", "Error de registro", javax.swing.JOptionPane.ERROR_MESSAGE); 
            }
        }catch (NumberFormatException ex) {
            // Captura si metieron letras en campos de precios o stock
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Por favor, verifique los precios y stocks. Asegúrese de ingresar solo números (Use punto para decimales).", 
                    "Error de Formato Numérico", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
       */
    }//GEN-LAST:event_aceptarActionPerformed

    private void generarSkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarSkuActionPerformed
String txtNombre = nombre.getText().trim();
    String txtMarca = marca.getText().trim();
    String txtTamano = tamano.getText().trim();

    // Validar que los campos no estén vacíos para evitar errores
    if (txtNombre.isEmpty() || txtMarca.isEmpty() || txtTamano.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, llena todos los campos para generar el SKU.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
        return; // Sale del método si falta información
    }

    // 2. Lógica para construir el SKU (Tomamos subcadenas para que no quede un texto gigante)
    // Ejemplo: Nombre "Arroz" -> "ARR", Marca "Costeña" -> "CO", Tamaño "1kg" -> "1KG"
    String parteNombre = (txtNombre.length() >= 3) ? txtNombre.substring(0, 3) : txtNombre;
    String parteMarca = (txtMarca.length() >= 2) ? txtMarca.substring(0, 2) : txtMarca;
    // Eliminamos espacios intermedios en el tamaño por si escriben "100 gr"
    String parteTamano = txtTamano.replace(" ", ""); 

    // 3. Concatenar y convertir a mayúsculas (sin guiones)
    String SKU = (parteNombre + parteMarca + parteTamano).toUpperCase();

    // 4. Mostrar el SKU en pantalla
    SKUgen.setText(SKU);
    }//GEN-LAST:event_generarSkuActionPerformed

    private void stockMinimo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockMinimo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockMinimo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                NuevoProductoDialog dialog = new NuevoProductoDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane SKUgen;
    private javax.swing.JButton aceptar;
    private javax.swing.JButton agregarTipo;
    private javax.swing.JButton generarSku;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField precio;
    private javax.swing.JTextField precioCompra;
    private javax.swing.JTextField stock;
    private javax.swing.JTextField stockMinimo1;
    private javax.swing.JTextField tamano;
    private javax.swing.JComboBox<String> tipoProducto;
    // End of variables declaration//GEN-END:variables
}
